<?php
/**
 * @title Studies
 * @author AnderEño (ander_frago@cuatrovientos.org)
 * @see CV can have multiple Studies
 */

namespace AppBundle\Entity\CvMgr;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="studies")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CvMgr\StudiesRepository")
 */
class Studies {

  /**
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @ORM\Column(name="vCategory", type="string", length=255)
   */
  private $vCategory;

  /**
   * @ORM\Column(name="vStudiesCode", type="string", length=255)
   */
  private $vStudiesCode;

  /**
   * @ORM\Column(name="vStudiesLevel", type="string", length=255)
   */
  private $vStudiesLevel;

  /**
   * @ORM\Column(name="vStudiesCentre", type="string", length=255)
   */
  private $vStudiesCentre;

  /**
   * @ORM\Column(name="dStartDate", type="date")
   */
  private $dStartDate;

  /**
   * @ORM\Column(name="dEndDate", type="date")
   */
  private $dEndDate;

  /**
   * @ORM\Column(name="vDescription", type="string", length=450, nullable=true)
   */
  private $vDescription;

  /**
   * @see Autogenerated Getters & Setters
   */
  public function setId($id) {
    return $this->id =$id;
  }
  public function getId() {
    return $this->id;
  }

  public function setVCategory($vCategory) {
    $this->vCategory = $vCategory;
  }

  public function getVCategory() {
    return $this->vCategory;
  }

  public function setVStudiesCode($vStudiesCode) {
    $this->vStudiesCode = $vStudiesCode;
  }

  public function getVStudiesCode() {
    return $this->vStudiesCode;
  }

  public function setVStudiesLevel($vStudiesLevel) {
    $this->vStudiesLevel = $vStudiesLevel;
  }

  public function getVStudiesLevel() {
    return $this->vStudiesLevel;
  }

  public function setVStudiesCentre($vStudiesCentre) {
    $this->vStudiesCentre = $vStudiesCentre;
  }

  public function getVStudiesCentre() {
    return $this->vStudiesCentre;
  }

  public function setDStartDate($dStartDate) {
    $this->dStartDate = $dStartDate;
  }

  public function getDStartDate() {
    return $this->dStartDate;
  }

  public function setDEndDate($dEndDate) {
    $this->dEndDate = $dEndDate;
  }

  public function getDEndDate() {
    return $this->dEndDate;
  }

  public function setVDescription($vDescription) {
    $this->vDescription = $vDescription;
  }

  public function getVDescription() {
    return $this->vDescription;
  }

  /**
   * @ORM\ManyToOne(targetEntity="CV", inversedBy="studies", cascade={"persist"})
   * @ORM\JoinColumn(name="cv_id", referencedColumnName="id")
   */
  private $cv;

  public function getCv() {
    return $this->cv;
  }

  public function setCv($cv) {
    $this->cv = $cv;
  }

}

