security:
    # En el caso que los usuarios tengan la contraseña cifrada configuramos los encoders para la entidad en la que estén los usuarios
    encoders:
        AppBundle\Entity\UserMgr\User:
            algorithm: bcrypt
            cost: 4
    role_hierarchy:
        ROLE_USER: [ROLE_USER_FORMER_STUDENTS, ROLE_USER_EMPLOYEERS]
        ROLE_ADMIN: [ROLE_ARTEAN]

    # En providers le indicamos que los usuarios van a salir de la base de datos y el username será email
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:UserMgr\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~

            guard:
                authenticators:
                - AppBundle\Security\LoginFormAuthenticator

    access_control:
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, role: [ROLE_ARTEAN] }
    - { path: ^/offers/(.+), role: [IS_AUTHENTICATED_FULLY] }
    - { path: ^/cv/new, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/cv/search, role: [ROLE_USER_EMPLOYEERS] }


