<?php
/**
 * @title Curriculum Vitae Categories
 * @author AnderEño (ander_frago@cuatrovientos.org)
 * @see Entity to configure the different types of WorkExperiences,
 * Studies, Languages... that can be registered in the system.
 * This entity is used when filtering in Cv search web page.
 */

namespace App\Entity\CvMgr;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="cv_categories")
 * @ORM\Entity(repositoryClass="App\Repository\CvMgr\CVCategoriesRepository")
 */
class CVCategories {
  /**
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;
  /**
   * @ORM\Column(name="vKey", type="string", length=255)
   */
  private $key;
  /**
   * @ORM\Column(name="vValue", type="string", length=255)
   */
  private $value;
  /**
   * @ORM\Column(name="vDescription", type="string", length=255)
   */
  private $description;

  /**
   * @see Autogenerated Getters & Setters
   */

  public function getId() {
    return $this->id;
  }

  public function setId(int $id) {
    $this->id = $id;
  }

  public function getKey() {
    return $this->key;
  }
  public function setKey($key) {
    $this->key = $key;
  }

  public function getValue() {
    return $this->value;
  }
  public function setValue($value) {
    $this->value = $value;
  }

  public function getDescription() {
    return $this->description;
  }
  public function setDescription($description) {
    $this->description = $description;
  }

  public function __toString(){
    // to show the name of the Category in the select
    return $this->value;
  }
}