<?php
/**
 * @title Work Experiences
 * @author AnderEño (ander_frago@cuatrovientos.org)
 * @see CV can have multiple Work experiences
 */

namespace App\Entity\CvMgr;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="work_experiences")
 * @ORM\Entity(repositoryClass="App\Repository\CvMgr\WorkExperiencesRepository")
 */
class WorkExperiences {

  /**
   * @var int
   *
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @var string
   *
   * @ORM\Column(name="vPosition", type="string", length=255)
   */
  private $vPosition;

  /**
   * @var string
   *
   * @ORM\Column(name="vEmployer", type="string", length=255)
   */
  private $vEmployer;

  /**
   * @var string
   *
   * @ORM\Column(name="vLocation", type="string", length=255)
   */
  private $vLocation;

  /**
   * @var string
   *
   * @ORM\Column(name="ltextDuties", type="text")
   */
  private $ltextDuties;

  /**
   * @var DateTime
   *
   * @ORM\Column(name="dStartDate", type="date")
   */
  private $dStartDate;

  /**
   * @var DateTime
   *
   * @ORM\Column(name="dEndDate", type="date")
   */
  private $dEndDate;


  /**
   * @see Autogenerated Getters & Setters
   */
  public function setId($id) {
    return $this->id =$id;
  }
  public function getId() {
    return $this->id;
  }

  public function setVPosition($vPosition) {
    $this->vPosition = $vPosition;
  }
  public function getVPosition() {
    return $this->vPosition;
  }

  public function setVEmployer($vEmployer) {
    $this->vEmployer = $vEmployer;
  }
  public function getVEmployer() {
    return $this->vEmployer;
  }

  public function setVLocation($vLocation) {
    $this->vLocation = $vLocation;

  }
  public function getVLocation() {
    return $this->vLocation;
  }

  public function setLtextDuties($ltextDuties) {
    $this->ltextDuties = $ltextDuties;
  }
  public function getLtextDuties() {
    return $this->ltextDuties;
  }

  public function setDStartDate($dStartDate) {
    $this->dStartDate = $dStartDate;
  }
  public function getDStartDate() {
    return $this->dStartDate;
  }

  public function setDEndDate($dEndDate) {
    $this->dEndDate = $dEndDate;
  }
  public function getDEndDate() {
    return $this->dEndDate;
  }

  /**
   * @ORM\ManyToOne(targetEntity="CV", inversedBy="workexperiences", cascade={"persist"})
   * @ORM\JoinColumn(name="cv_id", referencedColumnName="id")
   */
  private $cv;

  public function getCv() {
    return $this->cv;
  }
  public function setCv($cv) {
    $this->cv = $cv;
  }

}

